import express from "express";
import { verifyUser } from "../../Middleware/Auth.middleware.js";
import TaskController from "../../Controllers/Task/Task.controller.js";
import { uploadTask } from "../../Middleware/Upload.middleware.js";

const router = express.Router();

router.post(
  "/",
  verifyUser([
    "FACTORYMANAGER",
    "ENGINEERING",
    "HumanResource",
    "MotherCompany",
  ]),
  uploadTask.single("task"),
  TaskController.createTask
);

router.get(
  "/all",
  verifyUser([
      "CUTTING",
      "DRAWING",
      "ENGINEERING",
      "FACTORYMANAGER",
      "PRINTING",
      "QUALITYASSURANCE",
      "TAILORING",
      "WAREHOUSEMANAGER",
      "HumanResource",
      "MotherCompany",
      "Accounting",
      "Monitoring",
      "PRODUCTION"
  ]),
  TaskController.getAllTasks
);
router.get(
  "/:id",
  verifyUser([
      "CUTTING",
      "DRAWING",
      "ENGINEERING",
      "FACTORYMANAGER",
      "PRINTING",
      "QUALITYASSURANCE",
      "TAILORING",
      "WAREHOUSEMANAGER",
      "HumanResource",
      "MotherCompany",
      "Accounting",
      "Monitoring",
      "PRODUCTION"
  ]),
  TaskController.getTaskById
);
router.get(
  "/start/:id",
  verifyUser([
      "CUTTING",
      "DRAWING",
      "ENGINEERING",
      "FACTORYMANAGER",
      "PRINTING",
      "QUALITYASSURANCE",
      "TAILORING",
      "WAREHOUSEMANAGER",
      "HumanResource",
      "MotherCompany",
      "Accounting",
      "Monitoring",
      "PRODUCTION"
  ]),
  TaskController.startTask
);
router.get(
  "/",
  verifyUser([
    "FACTORYMANAGER",
    "ENGINEERING",
    "HumanResource",
    "MotherCompany",
  ]),
  TaskController.getTaskNames
);

router.get(
  "/current/task",
  verifyUser([
      "CUTTING",
      "DRAWING",
      "ENGINEERING",
      "FACTORYMANAGER",
      "PRINTING",
      "QUALITYASSURANCE",
      "TAILORING",
      "WAREHOUSEMANAGER",
      "HumanResource",
      "MotherCompany",
      "Accounting",
      "Monitoring",
      "PRODUCTION"
  ]),
  TaskController.getCurrentTasks
);

router.get(
  "/search/:query",
  verifyUser([
      "CUTTING",
      "DRAWING",
      "ENGINEERING",
      "FACTORYMANAGER",
      "PRINTING",
      "QUALITYASSURANCE",
      "TAILORING",
      "WAREHOUSEMANAGER",
      "HumanResource",
      "MotherCompany",
      "Accounting",
      "Monitoring",
      "PRODUCTION"
  ]),
  TaskController.searchTasks
);

router.delete(
  "/:id",
  verifyUser(["FACTORYMANAGER", "ENGINEERING"]),
  TaskController.deleteTask
);
router.put(
  "/:id",
  verifyUser([
      "CUTTING",
      "DRAWING",
      "ENGINEERING",
      "FACTORYMANAGER",
      "PRINTING",
      "QUALITYASSURANCE",
      "TAILORING",
      "WAREHOUSEMANAGER",
      "HumanResource",
      "MotherCompany",
      "Accounting",
      "Monitoring",
      "PRODUCTION"
  ]),
  uploadTask.single("task"),
  TaskController.updateTask
);
router.get(
  "/feedback/:id",
  verifyUser([
      "CUTTING",
      "DRAWING",
      "ENGINEERING",
      "FACTORYMANAGER",
      "PRINTING",
      "QUALITYASSURANCE",
      "TAILORING",
      "WAREHOUSEMANAGER",
      "HumanResource",
      "MotherCompany",
      "Accounting",
      "Monitoring",
      "PRODUCTION"
  ]),
  TaskController.getSubmitFeedback
);
router.put(
  "/feedback/:id",
  verifyUser([
      "CUTTING",
      "DRAWING",
      "ENGINEERING",
      "FACTORYMANAGER",
      "PRINTING",
      "QUALITYASSURANCE",
      "TAILORING",
      "WAREHOUSEMANAGER",
      "HumanResource",
      "MotherCompany",
      "Accounting",
      "Monitoring",
      "PRODUCTION"
  ]),
  uploadTask.single("task"),
  TaskController.submitFeedback
);

const TaskRoute = router;
export { TaskRoute };
